### PR TITLE
setting up the README.md

### PR DESCRIPTION
**Pull request by jackcarlisle**

### CODE REVIEW

**Comment by iteles** [comment]
@jackcarlisle Does the assignment to @nelsonic mean this is ready to be merged? I wasn't sure because of the lack of description in the PR :blush:

**Comment by nelsonic** [comment]
@jackcarlisle _same_ question... are you going to add to this branch/PR or can I merge it?

**Comment by jackcarlisle** [comment]
@iteles Yes it's ready to be merged, I'll make sure I include a description next time!
@nelsonic I've switched to another branch that I'll be pushing to from now on so it's ok if you merge it!

**Comment by nelsonic** [comment]
Thanks. :+1:

**Pull request merged**
